service: myzaico

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  endpointType: REGIONAL
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-northeast-1'}
  apiGateway:
    apiKeySourceType: HEADER
  environment:
    DYNAMODB_ITEM_TABLE: ${self:service}-${opt:stage}-items
    DYNAMODB_USER_TABLE: ${self:service}-${opt:stage}-users
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMODB_ITEM_TABLE}
        - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMODB_USER_TABLE}

functions:
  createItem:
    handler: handlers/items/put.handler
    events:
      - http:
          path: items
          method: post
          cors: true
          private: true
  updateItem:
    handler: handlers/items/put.handler
    events:
      - http:
          path: items
          method: put
          cors: true
          private: true
  deleteItem:
    handler: handlers/items/delete.handler
    events:
      - http:
          path: items
          method: delete
          cors: true
          private: true
  getItem:
    handler: handlers/items/get.handler
    events:
      - http:
          path: items/{id}
          method: get
          cors: true
          private: true
  getAllItems:
    handler: handlers/items/getAll.handler
    events:
      - http:
          path: items
          method: get
          cors: true
          private: true
  updateUser:
    handler: handlers/users/put.handler
    events:
      - http:
          path: users
          method: put
          cors: true
          private: true
  getUser:
    handler: handlers/users/get.handler
    events:
      - http:
          path: users/{id}
          method: get
          cors: true
          private: true

resources:
  Resources:
    TestItemsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_ITEM_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    TestUsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_USER_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5